### ISSUE TITLE
[Onboarding] Fullnode subsidy from user transaction

### ISSUE THREAD

**Issue by lpgeiger** [OLSF/libra#382]
Fullnode onboarding takes multiple days since the fullnode rewards are only paid at epoch boundaries. 

This is done so that the system address is the only one that can mint directly, to add another layer of security.

Investigate if minting from user transactions can be done safely and with what guarantees.

**Comment by nelaturuk** [comment]
**Current Process for Node Onbording:** 

Epoch 0: 
 Step 1: Prospective validator creates a vdf proof and shares the json file with an existing validator.
 Step 2: Existing validator issues a transaction to add the new incoming validator in the validator set. 

Epoch 1: New validator gets the subsidy gas coins with which they can post the proof created. 
Epoch 2: New validator is in the validator set. 

**Problem:**

It should not take three epochs for a new validator to join the validator set and participate in consensus. 

**Proposed Options:**

1. When a validator bootstrapping transaction is issued, we mint subsidy tokens and deposit them to the prospective validator account. For which we need to grant access to validator account to mint tokens. 
2. Existing validator issues the bootstrapping transaction transfers the certain fixed amount of gas to the new validator account. 

Both the above options would allow for a  new validator to immediately post the proofs and participate in the validator set. 

**Solution**

We pick option 2 for now. It makes sense for an existing validator who is adding the new node to the set to pay the gas fees required by the new validator. This is instead of excessively minting tokens which is the way to go if we choose option 1. Also, we can avoid the issue of granting access to mint tokens to the validator. 

- The change is to transfer the fixed amount gas from the current validator to the newly created validator account. 
- We can use withdrawal limit implementation as a base and make this change.

**Additional Checks**

- Subsidy minting is still done by VM only. 
- Fixed amount of tokens being transferred. Nothing in excess. 
- In case the existing validator doesn't have enough balance, we still revert to the existing process of waiting for the next epoch for the subsidy to be granted by the VM.

**Comment by sm86** [comment]
I like the idea of transferring fixed amount gas from current validator to the new validator. This would also reduce minting of new coins for every wannabe validator on the network.

**Comment by lpgeiger** [comment]
closed with #409
