### ISSUE TITLE
Refactor Validator Universe

### ISSUE THREAD

**Issue by sm86** [OLSF/libra#397]
# ⏱ Optimization 

## Motivation

The validator universe has a list of miners who want to be validators on the network. This is a redundant replication of miner state. 
Validator Universe is a subset of Miner Pool. Proposal to use miner state to compute the validator universe on the go.  

## Approach
Each miner has a miner state with metadata such as number of epochs mined, proofs in last epoch, etc. We add extra fields such as jail-bit and also if a miner is interested in being a validator in the next epoch. 

The client should query which state it is currently in - miner pool, validator universe or validator set. 

The unit tests should be updated to work with these changes.

**Comment by lpgeiger** [comment]
>Validator Universe is a subset of Miner Pool. Proposal to use miner state to compute the validator universe on the go.
I think these are separate lists, with separate concerns.

ValidatorUniverse exists because there is no list anywhere in the system where we can query everyone that is configured as a validator. This list is needed for a number of loops that happen in epoch reconfiguration.

MinerState is not a list, but a struct on individual accounts.

In current code v4.2.7 there is a miner list, which only lists miners in the current epoch. This does not tell us if the account has the ValidatorConfig struct.

**Comment by sm86** [comment]
Got it. My bad, was confused between miner pool and validator universe.
