### ISSUE TITLE
CLI tools play nice with swarm.

### ISSUE THREAD

**Issue by lpgeiger** [OLSF/libra#469]
The swarm-path entry point should be usable across all 0L apps.

Cli
- [x] init,  initialize configs in swarm_temp and not in host root.
- [x] health
- [x] serve
- [x] pilot
- [x] explorer

Miner
- [x] start

Onboard
- [x] val

Txs 
- [x] transactions

**Comment by mortonbits** [comment]
With https://github.com/OLSF/libra/pull/508/ the following will work:
onboard val

* Also txs and miner will then work again for 4.3.1
* health command got broken since 4.3.1, I have to check this separately

**Comment by lpgeiger** [comment]
Here's an issue with Miner and Swarm. I'm still working to get a consistent reproduction of the issue.

> What are you trying to achieve. 
I'm a developer trying to run swarm, and have a miner send transactions as `alice`

> Be explicit about what version you are on (commit).
v4.3.1: ec3a7002e7063203f25fba6de0a65a0685ebc416

> What commands you have executed from a clean state, so that it is reproducible (ie. Starting with rm -rf ~/.0L)

```
# from my dev machine
rm -rf ~/.0L ~/swarm_temp

#started swarm
cd ~/libra/  && cargo build -p libra-node -p cli && cargo run -p libra-swarm -- --libra-node target/debug/libra-node -c ~/swarm_temp -n 1 -s --cli-path target/debug/cli'

# in another window
# init
cargo r -p ol -- --swarm-path ~/swarm_temp/ --swarm-persona alice init
# miner
cargo r -p miner -- --swarm-path ~/swarm_temp/ --swarm-persona alice start
```

> What was the expected result.
I expected a transaction to be sent.

> What was the outcome which was not expected.
Error connecting to a swarm node.

```
miner config file not existing: "/root/swarm_temp/0/0L.toml"
Info: Got tx params from swarm
Fetching remote tower height
Error fetching remote state: error sending request for url (http://localhost:34595/): error trying to connect: tcp connect error: Connection refused (os error 111)
```

**Comment by mortonbits** [comment]
Thanks for merging everything back into the main branch again.

When I worked for the miner to make it run with swarm, I only got to get it run when there there is a copy of the block_0.json of the fixtures in the blocks dir. I described this in the pull request https://github.com/OLSF/libra/pull/488:

cargo r -p ol-cli -- --swarm-path=.........../swarm_temp --swarm-persona=alice init
mkdir .........../swarm_temp/0/blocks
cp ol/fixtures/blocks/test/alice/* $SWARMDIR/0/blocks


Do you think that is ok? Which would mean that the documentation needs to be updated? I can take care about this.....

Otherwise what do you propose? One other possibility would be to let the "blocks" property directly point into ol/fixtures/blocks/test/alice/ folder. But then, there would be blocks created in the git repository and that could confuse someone when preparing a commit.

**Comment by lpgeiger** [comment]
Yes I think your last proposal is good, with one change. We should copy the block_0.json file to swarm_temp/0/blocks/ and also modify the 0L.toml so that it uses that path as the right "blocks" patch. That way the mining will be consistent.

**Comment by dikshu11** [comment]
The command `cargo r -p ol-cli -- --swarm-path=<swarm-path> --swarm-persona=alice init` initializes the host configs, and save `0L.toml` file to `<swarm-path>/0/0L.toml` path. This file contains the right "blocks" path. 

If same file is passed as path to the configuration file using `--config` flag as shown in the command `cargo r -p miner -- --swarm-path <swarm-path> --swarm-persona alice --config <swarm-path>/0/0L.toml  start`, miner worked. 

I used main branch for creating swarm and testing purpose.

**Comment by mortonbits** [comment]
With https://github.com/OLSF/libra/pull/510 it will be more stable. As then the "init" command also creates the blocks directory and copies the initial block there.

**Comment by mortonbits** [comment]
This issue is now fixed in my opinion.
