### ISSUE TITLE
[Bug] Intermittent Autopay2 behavior on FixedOnce Type

### ISSUE THREAD

**Issue by lpgeiger** [OLSF/libra#554]
I'm seeing intermittent errors with the FixedOnce autopay type. I see it in integration tests, and I think it's the same issue @earthwindfirewater had in his experimental network test.

Wonder if it's related to the tick of the autopay during the epoch.

To reproduce (At times you'll get the test to pass and at other times not.)

``` 
AUTOPAY_FILE=alice.fixed_once.autopay_batch make -f ol/integration-tests/test-autopay test
``` 

The times it doesn't pass I notice when I query `q ar <alice>` I will see an autopay config, and then in the next epoch I don't see anything in configs. If that helps.

**Comment by jamesmeijers** [comment]
This appears to be caused by the test setting the "duration_epochs" variable to 1, and the next epoch being entered before the transaction is sent. This way the first time the AP module sees the instruction, it has already expired and is rejected. 

There's two ways to fix this. First, setting "duration_epochs" to some value > 1. However, in hindsight the duration_epcohs variable should just be ignored for one time payments, the second option. 

In #556 I implement both changes. The first is to make the test always pass for the current stdlib, and the second is so that the AP one time payments module ignores the duration parameters to make it more clear to users.

**Comment by lpgeiger** [comment]
Thanks for this. Nice catch.
Until the stdlib changes propagate, should we just adjust the rust parser of the autopay_batch.json, to update the value to 2, and instruct people to not place a duration field in the json.
