### ISSUE TITLE
[Tower] args for using alternate URL not working --upstream-url and --url

### ISSUE THREAD

**Issue by 0o-de-lally** [OLSF/libra#769]
Submitting transactions from Tower usually use a default_node's IP address, described in 0L.toml.

This can be modified in CLI with --upstream-url (which will select a random peer from the list defined in upstream_peers in 0L.toml) and --url which takes the URL from commandline.

Both of those  arguments are instead still only using the default_node. 

The issue can cause other instability: if your default_node is defined as localhost, and your local node is not synced, many transactions will fail, or fail to update status. You should be able to easily choose another URL, but this is not failing. The only remedy for now is to update the 0L.toml file, and replace the default_node.

**Comment by sm86** [comment]
Error: 
`Fetching remote tower height: http://xx.yy.zz.abc/, addr
Error fetching remote state: Error { inner: Inner { kind: Request, source: Some(ConnectionFailed("connection timed out")), json_rpc_error: None } }`
`Caused by:
    Connection Failed: connection timed out
WARN: Failed fetching remote state: Error fetching remote state: Error { inner: Inner { kind: Request, source: Some(ConnectionFailed("connection timed out")), json_rpc_error: None } }`
`Caused by:
    Connection Failed: connection timed out
url: http://xx.yy.zz.abc/ `

I tried with a few IP addresses

**Comment by mortonbits** [comment]
Fixed the documentation in file recover_validator_if_it_stops_mining_and_falls_out_of_validator_set.md in PR https://github.com/OLSF/libra/pull/763
